### ISSUE TITLE
Bad geometry when pads too close

### ISSUE THREAD

**Issue by emmakbat** [qnngroup/qnngds#86]
When East/West pads would be placed too close to North/South pads, I encounter strange behavior:
![Screenshot from 2024-10-23 14-31-22](https://github.com/user-attachments/assets/162b77d4-f10b-42a7-a49b-46ce8cad6059)

Basically, although the ports have the right orientation, it seems as though the routing goes up instead of straight to the right, leading to a misshapen pad

**Comment by emmakbat** [comment]
![PHIDL_quickplot](https://github.com/user-attachments/assets/ef48d5f0-bd91-4409-84be-28a5ecfc79a0)
The issue appears to arise because of the placement of the inner ports within the device_max_size when a cell is particularly crowded. This could be alleviated by dynamically changing the orientation of the pad port to minimize distance to the inner_port, or by adding an option to manually relax the device_max_size for cells the user knows will have a lot of space taken up by pads and relatively little taken up by devices

**Comment by reed-foster** [comment]
maybe this will be helpful: https://github.com/qnngroup/qnngds/blob/f8d192d79bc13ca5d742fcb683f4dcb2cfc6768c/src/qnngds/utilities.py#L194
